# When installed, in AdGuard Home, configure your SSL certificate manually for DoH/DoT
name: adguardhome
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"      # DNS
      - "53:53/udp"      # DNS
      #- "67:67/udp"      # DHCP server
      #- "68:68/udp"      # DHCP client
      #- "80:80/tcp"      # HIDE THIS IF USING SSL: Admin web UI (HTTP) - expose only via reverse proxy or keep internal
      #- "443:443/tcp"    # Admin web interface (HTTPS) and DNS-over-HTTPS (DoH)
      #- "443:443/udp"    # DNS-over-HTTPS (DoH)
      #- "3000:3000/tcp"  # Initial setup web interface (can close after initial wizard)
      - "853:853/tcp"    # DNS-over-TLS (DoT) and DNS-over-QUIC (DoQ)
      - "853:853/udp"    # DNS-over-QUIC (DoQ)
      - "5443:5443/tcp"  # DNSCrypt
      - "5443:5443/udp"  # DNSCrypt
      - "6060:6060/tcp"  # Profiling / debugging
    volumes:
      - ${SERVER_DATA_FOLDER:-/root/labdata}/adguard-home/work:/opt/adguardhome/work
      - ${SERVER_DATA_FOLDER:-/root/labdata}/adguard-home/conf:/opt/adguardhome/conf
      - ${SERVER_DATA_FOLDER:-/root/labdata}/adguard-home/ssl_ca:/usr/local/share/ca-certificates
      - ${SERVER_DATA_FOLDER:-/root/labdata}/ssl_certs:/root/ssl_certs
    networks:
      - app-net

networks:
    app-net:
      name: ${NETWORK_NAME:-adguard-bridge}