name: homeassistant
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${SERVER_DATA_FOLDER:-/root/labdata}/homeassistant/config:/config
      - ${SERVER_DATA_FOLDER:-/root/labdata}/ssl_certs:/ssl_certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    stop_grace_period: 60s
    privileged: true
    network_mode: host
    environment:
      TZ: ${TZ:-Europe/London}